"""Markets HTTP surface: macro news + portfolio-specific news.

Earnings endpoints now live in ``app/stocks/`` — the Markets page no
longer exposes an earnings tab. Keep this router focused on two things:

  * ``GET /markets/news``           — broad market news (RSS + Finnhub).
  * ``GET /markets/portfolio-news`` — per-holding company-news digest for
                                      the signed-in user's book.
"""

from __future__ import annotations

from fastapi import APIRouter, Depends
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.auth.service import get_current_user
from app.database.engine import get_async_session
from app.database.models import Position, User
from app.stocks.schemas import PortfolioNewsResponse
from app.stocks.service import aggregate_portfolio_news

from .ai_service import enrich_portfolio_news
from .schemas import MarketNewsResponse
from .service import fetch_market_news

router = APIRouter(prefix="/markets", tags=["markets"])


@router.get("/news", response_model=MarketNewsResponse)
async def get_market_news(current_user: User = Depends(get_current_user)):
    """Market summary headlines and recent development articles.

    Each headline and development card carries an ``ai_summary`` generated by
    the markets LLM. Summaries are batched into at most two Gemini calls per
    payload and cached for 30 minutes per article URL, so the AI path stays
    well within free-tier rate limits.
    """
    from .ai_service import enrich_news_payload

    data = await fetch_market_news()
    enriched = await enrich_news_payload(data)

    return {
        "summary": {
            "headlines": enriched["headlines"],
            "updated_at": enriched["updated_at"],
        },
        "developments": {
            "articles": enriched["articles"],
            "updated_at": enriched["updated_at"],
        },
        "sources": enriched.get("sources", []),
    }


@router.get("/portfolio-news", response_model=PortfolioNewsResponse)
async def get_portfolio_news(
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_async_session),
):
    """News aggregated across every symbol the user currently holds.

    Pulls up to 3 recent company-news items per holding, de-duplicates by
    URL, sorts newest-first, and runs a single batched Gemini call to
    attach a 3-bullet ``ai_summary`` to each card. When the LLM is offline
    or rate-limited the endpoint still returns the raw headlines.
    """
    stmt = select(Position).where(Position.user_id == current_user.id)
    positions = (await db.execute(stmt)).scalars().all()

    symbols: list[str] = []
    seen: set[str] = set()
    for p in positions:
        sym = (p.symbol or "").upper()
        if not sym or sym in seen or (p.quantity or 0) <= 0:
            continue
        seen.add(sym)
        symbols.append(sym)

    agg = await aggregate_portfolio_news(symbols, per_symbol=3, total_limit=24)

    if agg.articles:
        raw = [
            {
                "title": a.headline,
                "summary": a.summary,
                "source": a.source,
                "url": a.url,
            }
            for a in agg.articles
        ]
        enriched = await enrich_portfolio_news(raw)
        for card, meta in zip(agg.articles, enriched):
            card.ai_summary = meta.get("ai_summary")
            card.sentiment = meta.get("sentiment")

    return agg
