from datetime import datetime, timezone

from fastapi import APIRouter, Depends, HTTPException, Query

from app.auth.service import get_current_user
from app.database.models import User

from .ai_service import enrich_news_payload, generate_earnings_highlights
from .schemas import (
    EarningsCalendarResponse,
    EarningsHighlightsResponse,
    EarningsListResponse,
    MarketNewsResponse,
)
from .service import (
    fetch_earnings_calendar,
    fetch_earnings_for_date,
    fetch_market_news,
)

router = APIRouter(prefix="/markets", tags=["markets"])


@router.get("/news", response_model=MarketNewsResponse)
async def get_market_news(current_user: User = Depends(get_current_user)):
    """Market summary headlines and recent development articles.

    Each headline and development card carries an ``ai_summary`` generated by
    the markets LLM. Summaries are batched into at most two Gemini calls per
    payload and cached for 30 minutes per article URL, so the AI path stays
    well within free-tier rate limits.
    """
    data = await fetch_market_news()
    enriched = await enrich_news_payload(data)

    return {
        "summary": {
            "headlines": enriched["headlines"],
            "updated_at": enriched["updated_at"],
        },
        "developments": {
            "articles": enriched["articles"],
            "updated_at": enriched["updated_at"],
        },
        "sources": enriched.get("sources", []),
    }


@router.get("/earnings/calendar", response_model=EarningsCalendarResponse)
async def get_earnings_calendar(
    date: str | None = Query(
        None, description="Center date YYYY-MM-DD; defaults to today"
    ),
    current_user: User = Depends(get_current_user),
):
    """Weekly earnings calendar strip."""
    return await fetch_earnings_calendar(date)


@router.get("/earnings/date", response_model=EarningsListResponse)
async def get_earnings_for_date(
    date: str = Query(..., description="Date YYYY-MM-DD"),
    current_user: User = Depends(get_current_user),
):
    """Detailed earnings entries for a given date."""
    return await fetch_earnings_for_date(date)


@router.get("/earnings/highlights", response_model=EarningsHighlightsResponse)
async def get_earnings_highlights(
    symbol: str = Query(..., min_length=1, max_length=12),
    quarter: int = Query(..., ge=1, le=4),
    year: int = Query(..., ge=1990, le=2100),
    company: str = Query("", description="Company display name (optional)"),
    eps_estimate: float | None = Query(None),
    eps_actual: float | None = Query(None),
    revenue_estimate: float | None = Query(None),
    revenue_actual: float | None = Query(None),
    reported: bool = Query(True),
    current_user: User = Depends(get_current_user),
):
    """AI-generated highlights brief for a single earnings event.

    Payload is markdown intended for direct rendering in the UI. Output is
    cached per ``(symbol, quarter, year)`` for 1 hour.
    """
    try:
        highlights = await generate_earnings_highlights(
            symbol=symbol,
            company=company or symbol,
            quarter=quarter,
            year=year,
            eps_estimate=eps_estimate,
            eps_actual=eps_actual,
            revenue_estimate=revenue_estimate,
            revenue_actual=revenue_actual,
            reported=reported,
        )
    except Exception as exc:  # noqa: BLE001 — never bubble raw LLM errors to clients
        raise HTTPException(
            status_code=502,
            detail=f"Earnings AI temporarily unavailable: {exc}",
        ) from exc

    return {
        "symbol": symbol.upper(),
        "quarter": quarter,
        "year": year,
        "highlights": highlights,
        "generated_at": datetime.now(timezone.utc).isoformat(),
    }
