from __future__ import annotations

from pydantic import BaseModel


class MarketSource(BaseModel):
    """A news outlet that actually contributed to the current payload."""

    name: str
    url: str


class MarketHeadline(BaseModel):
    title: str
    # ``summary`` is the raw excerpt pulled from the upstream feed (fallback).
    summary: str
    # ``ai_summary`` is the polished 3–4 sentence summary generated by the
    # markets agent. Optional so the endpoint degrades gracefully when the
    # LLM is disabled, rate-limited, or errors out mid-batch.
    ai_summary: str | None = None
    source: str
    url: str


class MarketSummaryResponse(BaseModel):
    headlines: list[MarketHeadline]
    updated_at: str


class RecentDevelopment(BaseModel):
    source: str
    time_ago: str
    title: str
    # ``excerpt`` is the raw upstream snippet; ``ai_summary`` is the tight
    # 1–2 sentence card copy. Frontend prefers ai_summary when present.
    excerpt: str
    ai_summary: str | None = None
    url: str


class RecentDevelopmentsResponse(BaseModel):
    articles: list[RecentDevelopment]
    updated_at: str


class MarketNewsResponse(BaseModel):
    summary: MarketSummaryResponse
    developments: RecentDevelopmentsResponse
    sources: list[MarketSource]
