"""Print frozenset literal lines for ``export_aggregator._ETF_SYMBOLS``.

Run from repo root::

    python scripts/_gen_etf_symbols.py

Paste the output (minus the ``# N symbols`` line) into ``export_aggregator.py``,
or replace the existing ``frozenset({ ... })`` body.
"""
from __future__ import annotations

# Curated US-listed ETFs: Vanguard, iShares, SPDR, Schwab, Invesco, ARK, ProShares,
# Direxion, Global X, VanEck, WisdomTree, Dimensional, Avantis, PIMCO, JPMorgan,
# commodity, bond, intl, thematic, leveraged. ~600+ symbols; not every US ETF
# (3000+) — use a security master API for true completeness.
SYMS = """
AAA AADR AAXJ ACES ACIM ACIO ACWI ACWV ACWX AIA AIRR AIQ AIVI AIVL ALTL AMJ AMOM AMLP AMZA ANGL
AOA AOK AOM AOR ARGT ARKB ARKG ARKK ARKQ ARKW ARKX ASHR ASHS ATMP AUGM AVDE AVEM AVIG AVLV AVSC AVUS AVUV
AWAY BAB BAL BATT BBAX BBCA BBJP BBUS BCD BCI BDRY BETZ BFIT BIB BIL BINC BITB BITI BITO BKLN BLV BIV
BIZD BJK BLOK BND BNDW BNDX BOIL BOTZ BRZU BTEC BUG CANE CARZ CCOR CDC CDL CEFS CFA CIBR CLOU CNXT COM
COMT COPX CORN CPER CRAK CRBN CURE CVY CWB CWBC CWI DBA DBC DBEF DBJP DBO DEFA DEM DES DEUS DEW DFAC
DFAE DFAU DFAX DFAI DFAR DFAS DFAT DFEM DFEV DFEA DFUS DFUV DGRO DGS DIHP DIM DIVO DLS DNL DRIP DRIV DSI
DTD DTH DVY DWAS DWX DXJ EBND ECH EDEN EDIV EDV EEM EEMS EEMV EES EEV EFA EFAD EFAV EFG EFIV EIDO EINC
EIRL EIS EMB EMLC EMMF EMQQ ENOR ENZL EPHE EPI EPOL EPS EQAL ESGD ESGE ESGU ESGV ESML ESPO ETHA ETHE
EUFN EUFX EWA EWC EWD EWG EWH EWI EWJ EWK EWL EWM EWN EWP EWQ EWS EWT EWUS EWW EWY EWZ EWZS EXI EZA EZBC
EZU FAD FAS FAZ FBCG FBND FBTC FCVT FDN FDNI FEM FENY FEZ FEX FFEB FGD FGM FHA FIW FLAX FLEX FLOT FLRN
FM FMQQ FMX FNDA FNDC FNDE FNGD FNGU FNRG FPE FPX FRDM FREL FRN FSTA FTCS FTEC FTGC FTLS FV FVAL FXD FXI
FXL FXY GAMR GBIL GBTC GDE GDX GDXJ GEM GHYB GLD GLDM GLIN GLL GLTR GMET GMOM GOAU GOEX GOVT GREK GSG
GUNR GUSH GVI GVIP GWX HACK HAIL HAP HAUZ HAWX HDV HEFA HEWJ HEZU HIBL HIBS HYDW HYEM HYG HYLB HYLS HYMB HYS
IAGG IAI IAK IAT IAUM IBB IBIT IBND IBO IBUY ICLN IDX IEF IEFA IEI IEMG IEV IGF IGIB IGM IGOV IGSB IGV IHF
IHE IHI IJH IJK IJR INCO INDA INDL INDY ITB ITM ITOT IUSB IVOG IVOL IVOO IVV IVW IWB IWC IWD IWF IWM IWN
IWO IWP IWR IWS IWV IWX IWY IYT IYZ JEPI JEPQ JPST JPME KBWY KBA KBE KOLD KRE KSA KWEB LABD LABU LIT LQD MBB
MCHI MDY MJ MORT MSOS MTUM MUB NAIL NEAR NOBL NORW NUSI OEF OIH OUNZ PALL PAVE PBW PCEF PCY PDBC PFF PFFD
PFFR PFXF PGJ PHB PICK PILL PIN PLTM PPLT PSIL PST PSQ PZA QAI QCLN QID QLD QQQ QQQE QQEW QQQM QTEC QUAL
QYLD REMX RING RSP RSPA RSPM RWL RWR RYLD SATO SCHB SCHC SCHD SCHE SCHF SCHG SCHH SCHJ SCHM SCHP SCHQ SCHV
SCHX SCHY SCHZ SDOW SDY SFY SGOL SH SHY SHYG SIL SILJ SJNK SKF SLV SMBS SMH SMIN SNSR SOXL SOXS SOXX SPGP
SPLG SPLV SPMO SPTI SPTL SPTM SPXL SPXS SPXU SPY SPYD SPYG SPYV SQQQ SRLN SRVR SSO STIP SUB TAN TBT TECL
TECS TFI TFLO THD THNQ TIP TLH TLT TMF TMV TNA TQQQ TTT TUR TWM TZA UBT UCO UDOW UGA UGL UNG UPRO UPW URA
URNM USCI USFR USMV USO UUP UWM UYG VCIT VCLT VCR VCSH VDC VDE VEA VEU VFMO VFH VGIT VGK VGLT VGSH VGT VHT
VIG VIS VLU VMBS VNQ VNQI VO VOE VONG VONV VOO VOOG VOOV VOT VOX VPL VPU VRP VSGX VT VTEB VTI VTIP VTV VTWG
VTWO VTWV VUG VUSB VWO VWOB VXF VXUS VYM VYMI WCLD WEAT WEBL WEBS XAR XBI XES XHB XHE XHS XLB XLC XLE XLF
XLI XLK XLP XLRE XLU XLV XLY XME XMLV XOP XPH XRT XSD XSLV XSMO XSVM XSW XTN XWEB XYLD YANG YINN YOLO ZROZ ZSL
DIA SPAB SPLB SPHY SPEM SPEU SPSM SPSB SPUS SPDW IXUS IDEV IYY IEUR IQLT
""".split()

BAD = {
    "IT", "AI", "ON", "AN", "BE", "HAS", "NOW", "LOW", "KEY", "DDS", "FUN", "JOB",
    "REXX",  # not a standard ETF ticker
}
syms = sorted({s.strip().upper() for s in SYMS if len(s.strip()) >= 2} - BAD)
print(f"# {len(syms)} ETF symbols (curated, not all US-listed ETFs)")
for i in range(0, len(syms), 10):
    chunk = syms[i : i + 10]
    print('    "' + '", "'.join(chunk) + '",')
